name: deploy

on:
  push:
    branches: [ "release/*", "master" ]

jobs:
  build:
    runs-on: macos-12  
    steps: 
    - uses: actions/checkout@v3

    - name: Force Xcode 13
      run: sudo xcode-select -s /Applications/Xcode_13.4.1.app
