name: Run build

on:
# develop 브랜치에 push, pull_request Event 발생 시 jobs를 실행합니다.
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Workflow가 실행할 jobs
jobs:
  build:
    runs-on: macos-12 
    
    # job의 일부로 실행될 일런의 task
    steps: 
    - uses: actions/checkout@v3
    
    - name: Force Xcode 14
      run: sudo xcode-select -s /Applications/Xcode_13.4.1.app

       
    - name: Start Xcode build
      run: |
        xcodebuild clean build -project WaktaverseMusic/WaktaverseMusic.xcodeproj -scheme WaktaverseMusic -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.5'
