name: Run build

on:
# develop 브랜치에 push, pull_request Event 발생 시 jobs를 실행합니다.
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

# Workflow가 실행할 jobs
jobs:
  build:
    runs-on: macos-12 
    
    env: # 환경변수
      ENCRYPTED_SECURITY_FILE_PATH: ${{ '.github/secrets/Security.xcconfig.gpg' }}
      DECRYPTED_SECURITY_FILE_PATH: ${{ './WaktaverseMusic/' }}
      SECURITY_ENCRYPTION_KEY: ${{ secrets.SECURITY_ENCRYPTION_PWD }} # gpg로 파일 암호화할 때 사용한 암호 
      
    
    # job의 일부로 실행될 일런의 task
    steps: 
    - uses: actions/checkout@v3
    
    - name : Decrypt file
      run: |  
        echo `ls ./WaktaverseMusic/`
        gpg -d -o "$DECRYPTED_SECURITY_FILE_PATH" --pinentry-mode=loopback --passphrase "$SECURITY_ENCRYPTION_KEY" "$ENCRYPTED_SECURITY_FILE_PATH"

    - name: Force Xcode 13
      run: sudo xcode-select -s /Applications/Xcode_13.4.1.app

       
    - name: Start Xcode build
      run: |
        xcodebuild clean build -project WaktaverseMusic/WaktaverseMusic.xcodeproj -scheme WaktaverseMusic -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.5'
